backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - label: 'Categories'
    name: 'categories'
    folder: 'content/'
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - label: 'Cover Image'
        name: 'image'
        widget: 'file'
        media_library:
          config:
            multiple: true
      - { label: Cover OffsetX, name: offset_x, widget: number, default: 0 }
      - { label: Cover OffsetY, name: offset_y, widget: number, default: 0 }
      - label: 'Sub Categories'
        name: 'sub_categories'
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - label: 'Cover Image'
            name: 'image'
            widget: 'file'
            media_library:
              config:
                multiple: true
          - { label: OffsetX, name: offset_x, widget: number, default: 0 }
          - { label: OffsetY, name: offset_y, widget: number, default: 0 }
          - {
              label: Height,
              name: height,
              widget: select,
              options: ['1', '2', '3', '4', '5', '6'],
              default: '1',
            }
          - {
              label: Width,
              name: width,
              widget: select,
              options: ['1', '2', '3', '4', '5', '6'],
              default: '1',
            }
          - label: 'Gallery'
            name: 'gallery'
            widget: object
            fields:
              - label: Files
                name: files
                widget: list
                fields:
                  - label: 'File'
                    name: 'file'
                    widget: 'file'
                    media_library:
                      config:
                        multiple: true
                  - label: 'Video'
                    name: 'video'
                    required: false
                    widget: 'file'
                    media_library:
                      config:
                        multiple: true
